### ISSUE TITLE
Input improvements

### ISSUE THREAD

**Issue by brno32** [purple-technology/phoenix-components#118]
https://www.npmjs.com/package/floating-label-react has a few problems when it comes to our use case. It doesn't play nice with `styled-components` and setting types for customizing it isn't easy. Since it has problems with `styled-components` it has problems with server-side rendering

Also `<Input>`'s size should be adjustable

**Comment by samuelg0rd0n** [comment]
The component `floating-label-react` will not be used in the upcoming v4.
