### ISSUE TITLE
Using Link from next/link and LinkButton produces a console error

### ISSUE THREAD

**Issue by chorobin** [purple-technology/phoenix-components#181]
When using nextjs you use Link from next/Link to provide routing. You can provide a custom link styled component by providing a child of Link like in the following article

https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

If you use LinkButton as your custom component then you get the following console error:

  console.error
      Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
      
      Check the render method of `Styled(Component)`.

I think this is because LinkButton is not wrapped in a forwardRef call which will forward the ref to a the anchor element?

**Comment by samuelg0rd0n** [comment]
Yes, that's most probably the case. I'll make a fix. Thanks.

**Comment by samuelg0rd0n** [comment]
Released as version 4.10.0
