### ISSUE TITLE
Clicking CheckBox also highlights label text

### ISSUE THREAD

**Issue by brno32** [purple-technology/phoenix-components#40]
![checkbox_bug](https://user-images.githubusercontent.com/30541183/77163220-e7db0b00-6aad-11ea-9ef6-7fc6995309e4.gif)

**Comment by brno32** [comment]
@chromale I was looking at this and I'm not sure we want to do. It looks to me like we want the user to be able to click the text/label and for it to also trigger the `onClick` event? 

Does this matter enough to fix? We could disable the label as highlightable text, or separate it from the `<input>` element

**Comment by samuelg0rd0n** [comment]
Will be fixed in the upcoming v4.
