### ISSUE TITLE
Ensure props are passed between inter-dependent components

### ISSUE THREAD

**Issue by brno32** [purple-technology/phoenix-components#69]
For example we have customization via props in components like `Input` for props like `borderColor` that cannot be set in components like `DateInput`, which import `Input`. As we add customization to these parent elements, we need to make sure that customization is reflected in the child components as well and that all the necessary props are passed down

**Comment by samuelg0rd0n** [comment]
Props have been optimized in v4 and specifically `borderColor` prop is not relevant anymore so I'm closing this issue.
